import React from 'react';
import { render } from '@testing-library/react';
import RootLayout, { metadata } from '@/app/layout';

describe('RootLayout', () => {
  it('should have correct metadata', () => {
    expect(metadata).toEqual({
      title: 'Create Next App',
      description: 'Generated by create next app',
    });
  });

  it('should render children correctly', () => {
    const { getByText } = render(
      <RootLayout>
        <div>Test Child</div>
      </RootLayout>
    );
    expect(getByText('Test Child')).toBeInTheDocument();
  });
});
